"""paper trading columns

Revision ID: 47158d2e00c7
Revises: 9eb1b470da57
Create Date: 2026-06-06 15:27:12.424276
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '47158d2e00c7'
down_revision: str | None = '9eb1b470da57'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_positions', sa.Column('unrealized_pnl', sa.Numeric(precision=14, scale=4), nullable=True))
    op.alter_column('paper_positions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=24),
               existing_nullable=True)
    op.add_column('paper_trades', sa.Column('fees', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('paper_trades', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('paper_trades', 'fill_assumption',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('paper_trades', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=24),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper_trades', 'status',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('paper_trades', 'fill_assumption',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('paper_trades', 'closed_at')
    op.drop_column('paper_trades', 'fees')
    op.alter_column('paper_positions', 'status',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('paper_positions', 'unrealized_pnl')
    # ### end Alembic commands ###
