"""weather forecasts table

Revision ID: 5639d94d64fd
Revises: d3b54df49b13
Create Date: 2026-06-08 13:11:51.764930
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5639d94d64fd'
down_revision: str | None = 'd3b54df49b13'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecasts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('series_ticker', sa.String(length=64), nullable=True),
    sa.Column('event_ticker', sa.String(length=128), nullable=True),
    sa.Column('target_date', sa.String(length=16), nullable=True),
    sa.Column('station', sa.String(length=16), nullable=True),
    sa.Column('forecast_high_f', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_forecasts_event_time', 'weather_forecasts', ['event_ticker', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_forecasts_event_time', table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    # ### end Alembic commands ###
