"""weather settlements table

Revision ID: 58e9542edff8
Revises: 5639d94d64fd
Create Date: 2026-06-08 17:03:26.930394
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '58e9542edff8'
down_revision: str | None = '5639d94d64fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_settlements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_ticker', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('series_ticker', sa.String(length=64), nullable=True),
    sa.Column('target_date', sa.String(length=16), nullable=True),
    sa.Column('winning_ticker', sa.String(length=128), nullable=True),
    sa.Column('winning_subtitle', sa.String(length=64), nullable=True),
    sa.Column('actual_low_f', sa.Float(), nullable=True),
    sa.Column('actual_high_f', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_settlements_event_ticker'), 'weather_settlements', ['event_ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_settlements_event_ticker'), table_name='weather_settlements')
    op.drop_table('weather_settlements')
    # ### end Alembic commands ###
