"""initial schema

Revision ID: 9eb1b470da57
Revises:
Create Date: 2026-06-06 03:59:11.860661
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9eb1b470da57'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('portfolio_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_exposure', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('markets_scanned', sa.Integer(), nullable=False),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fills',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('kalshi_fill_id', sa.String(length=128), nullable=True),
    sa.Column('kalshi_order_id', sa.String(length=128), nullable=True),
    sa.Column('market_ticker', sa.String(length=128), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('action', sa.String(length=8), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('raw_fill_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_kalshi_fill_id'), 'fills', ['kalshi_fill_id'], unique=False)
    op.create_index(op.f('ix_fills_kalshi_order_id'), 'fills', ['kalshi_order_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('market_ticker', sa.String(length=128), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yes_bid', sa.Integer(), nullable=True),
    sa.Column('yes_ask', sa.Integer(), nullable=True),
    sa.Column('no_bid', sa.Integer(), nullable=True),
    sa.Column('no_ask', sa.Integer(), nullable=True),
    sa.Column('last_price', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('spread', sa.Integer(), nullable=True),
    sa.Column('midpoint', sa.Float(), nullable=True),
    sa.Column('liquidity_score', sa.Float(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_snapshots_ticker_time', 'market_snapshots', ['market_ticker', 'captured_at'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_source', sa.Text(), nullable=True),
    sa.Column('rules_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_ticker'), 'markets', ['ticker'], unique=True)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('market_ticker', sa.String(length=128), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yes_levels_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('no_levels_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('best_yes_bid', sa.Integer(), nullable=True),
    sa.Column('best_yes_ask', sa.Integer(), nullable=True),
    sa.Column('best_no_bid', sa.Integer(), nullable=True),
    sa.Column('best_no_ask', sa.Integer(), nullable=True),
    sa.Column('top_depth', sa.Integer(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orderbook_snapshots_ticker_time', 'orderbook_snapshots', ['market_ticker', 'captured_at'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('market_ticker', sa.String(length=128), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('market_ticker', sa.String(length=128), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('market_exposure', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('component', sa.String(length=48), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('market_ticker', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_type', sa.String(length=48), nullable=False),
    sa.Column('bot_mode', sa.String(length=20), nullable=False),
    sa.Column('implied_probability', sa.Float(), nullable=True),
    sa.Column('model_probability', sa.Float(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('input_snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['input_snapshot_id'], ['market_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_ticker_time', 'signals', ['market_ticker', 'created_at'], unique=False)
    op.create_table('live_orders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('kalshi_order_id', sa.String(length=128), nullable=True),
    sa.Column('market_ticker', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('action', sa.String(length=8), nullable=True),
    sa.Column('limit_price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('raw_order_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_orders_kalshi_order_id'), 'live_orders', ['kalshi_order_id'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('market_ticker', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('action', sa.String(length=8), nullable=True),
    sa.Column('assumed_price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('fill_assumption', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('exit_price', sa.Integer(), nullable=True),
    sa.Column('resolved_value', sa.Integer(), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('market_ticker', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('reason_codes_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('max_allowed_quantity', sa.Integer(), nullable=True),
    sa.Column('max_allowed_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_events')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_live_orders_kalshi_order_id'), table_name='live_orders')
    op.drop_table('live_orders')
    op.drop_index('ix_signals_ticker_time', table_name='signals')
    op.drop_table('signals')
    op.drop_table('system_events')
    op.drop_table('positions')
    op.drop_table('paper_positions')
    op.drop_index('ix_orderbook_snapshots_ticker_time', table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index(op.f('ix_markets_ticker'), table_name='markets')
    op.drop_table('markets')
    op.drop_index('ix_market_snapshots_ticker_time', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_fills_kalshi_order_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_kalshi_fill_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_table('bot_runs')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
