"""paper strategy columns

Revision ID: d3b54df49b13
Revises: 47158d2e00c7
Create Date: 2026-06-07 00:18:37.411655
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd3b54df49b13'
down_revision: str | None = '47158d2e00c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_positions', sa.Column('strategy', sa.String(length=24), nullable=True))
    op.create_index(op.f('ix_paper_positions_strategy'), 'paper_positions', ['strategy'], unique=False)
    op.add_column('paper_trades', sa.Column('strategy', sa.String(length=24), nullable=True))
    op.add_column('paper_trades', sa.Column('model_probability', sa.Float(), nullable=True))
    op.add_column('paper_trades', sa.Column('edge', sa.Float(), nullable=True))
    op.create_index(op.f('ix_paper_trades_strategy'), 'paper_trades', ['strategy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_trades_strategy'), table_name='paper_trades')
    op.drop_column('paper_trades', 'edge')
    op.drop_column('paper_trades', 'model_probability')
    op.drop_column('paper_trades', 'strategy')
    op.drop_index(op.f('ix_paper_positions_strategy'), table_name='paper_positions')
    op.drop_column('paper_positions', 'strategy')
    # ### end Alembic commands ###
